
<?php
// xamp local server "fix"
header("Access-Control-Allow-Origin: *, Content-Type: charset=UTF-8");
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap style -->
  <link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css">
  <!-- CSS style -->
  <link rel="stylesheet" type="text/css" href="../css/main.css">

  <!-- CDN -->

  <!-- Font style -->
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- Google Fonts -->
  <link href='https://fonts.googleapis.com/css?family=Passion+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Oxygen' rel='stylesheet' type='text/css'>

  <title>Test application</title>

</head>
<body>
 
